export default {
  ver: "v1",
  lang: "en",
  fname: "Brandon",
  userid: "BrandonS.2016",
  username: "Frankincense",
  avatarType: "dummy",
  avatarURL: "http://images-account.slooh.com/avatar-dummy.png",
  cid: "198265",
  at: "2",
  status: "Active",
  notifyType: "all",
  notifyStatus: "unread",
  notifyCount: "0",
  school: "",
  classroom: "",
  teacher: "",
  redirect: "",
  token: "3f0c15c24dd04a8d4f31f4ffba8bcdd71591d235",
  tokenExp: "",
  validate: "",
  loginError: "false",
  statusCode: "200"
}
