// flow-typed signature: f800bedf426acdfa71d00114fa0391bc
// flow-typed version: <<STUB>>/encodeurl_v^1.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'encodeurl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'encodeurl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'encodeurl/index' {
  declare module.exports: $Exports<'encodeurl'>;
}
declare module 'encodeurl/index.js' {
  declare module.exports: $Exports<'encodeurl'>;
}
