// flow-typed signature: e442285347a1c86231e33eb5b04f5b8d
// flow-typed version: <<STUB>>/enumify_v^1.0.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enumify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enumify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enumify/lib/enumify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enumify/lib/enumify.js' {
  declare module.exports: $Exports<'enumify/lib/enumify'>;
}
