// flow-typed signature: 8bb5a8f433782362fe00bcecb469ecf7
// flow-typed version: <<STUB>>/json-schema-traverse_v^0.3.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-schema-traverse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-schema-traverse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-schema-traverse/spec/fixtures/schema' {
  declare module.exports: any;
}

declare module 'json-schema-traverse/spec/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-schema-traverse/index' {
  declare module.exports: $Exports<'json-schema-traverse'>;
}
declare module 'json-schema-traverse/index.js' {
  declare module.exports: $Exports<'json-schema-traverse'>;
}
declare module 'json-schema-traverse/spec/fixtures/schema.js' {
  declare module.exports: $Exports<'json-schema-traverse/spec/fixtures/schema'>;
}
declare module 'json-schema-traverse/spec/index.spec.js' {
  declare module.exports: $Exports<'json-schema-traverse/spec/index.spec'>;
}
