// flow-typed signature: 0169d0724ab9b66f2a038d103073bbb6
// flow-typed version: <<STUB>>/qim_v0.0.52/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qim/$apply' {
  declare module.exports: any;
}

declare module 'qim/$begin' {
  declare module.exports: any;
}

declare module 'qim/$default' {
  declare module.exports: any;
}

declare module 'qim/$each' {
  declare module.exports: any;
}

declare module 'qim/$eachKey' {
  declare module.exports: any;
}

declare module 'qim/$eachPair' {
  declare module.exports: any;
}

declare module 'qim/$end' {
  declare module.exports: any;
}

declare module 'qim/$first' {
  declare module.exports: any;
}

declare module 'qim/$last' {
  declare module.exports: any;
}

declare module 'qim/$lens' {
  declare module.exports: any;
}

declare module 'qim/$merge' {
  declare module.exports: any;
}

declare module 'qim/$mergeDeep' {
  declare module.exports: any;
}

declare module 'qim/$nav' {
  declare module.exports: any;
}

declare module 'qim/$none' {
  declare module.exports: any;
}

declare module 'qim/$pick' {
  declare module.exports: any;
}

declare module 'qim/$pushContext' {
  declare module.exports: any;
}

declare module 'qim/$set' {
  declare module.exports: any;
}

declare module 'qim/$setContext' {
  declare module.exports: any;
}

declare module 'qim/$slice' {
  declare module.exports: any;
}

declare module 'qim/$traverse' {
  declare module.exports: any;
}

declare module 'qim/apply' {
  declare module.exports: any;
}

declare module 'qim/find' {
  declare module.exports: any;
}

declare module 'qim/has' {
  declare module.exports: any;
}

declare module 'qim/select' {
  declare module.exports: any;
}

declare module 'qim/set' {
  declare module.exports: any;
}

declare module 'qim/traverse' {
  declare module.exports: any;
}

declare module 'qim/umd/qim' {
  declare module.exports: any;
}

declare module 'qim/umd/qim.min' {
  declare module.exports: any;
}

declare module 'qim/update' {
  declare module.exports: any;
}

declare module 'qim/utils/arrayify' {
  declare module.exports: any;
}

declare module 'qim/utils/copy' {
  declare module.exports: any;
}

declare module 'qim/utils/createMerge' {
  declare module.exports: any;
}

declare module 'qim/utils/curry' {
  declare module.exports: any;
}

declare module 'qim/utils/getTypeErrorMessage' {
  declare module.exports: any;
}

declare module 'qim/utils/isNextNavigatorConstant' {
  declare module.exports: any;
}

declare module 'qim/utils/normalizeIndex' {
  declare module.exports: any;
}

declare module 'qim/utils/reduced' {
  declare module.exports: any;
}

declare module 'qim/utils/reduceSequence' {
  declare module.exports: any;
}

declare module 'qim/utils/removed' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qim/$apply.js' {
  declare module.exports: $Exports<'qim/$apply'>;
}
declare module 'qim/$begin.js' {
  declare module.exports: $Exports<'qim/$begin'>;
}
declare module 'qim/$default.js' {
  declare module.exports: $Exports<'qim/$default'>;
}
declare module 'qim/$each.js' {
  declare module.exports: $Exports<'qim/$each'>;
}
declare module 'qim/$eachKey.js' {
  declare module.exports: $Exports<'qim/$eachKey'>;
}
declare module 'qim/$eachPair.js' {
  declare module.exports: $Exports<'qim/$eachPair'>;
}
declare module 'qim/$end.js' {
  declare module.exports: $Exports<'qim/$end'>;
}
declare module 'qim/$first.js' {
  declare module.exports: $Exports<'qim/$first'>;
}
declare module 'qim/$last.js' {
  declare module.exports: $Exports<'qim/$last'>;
}
declare module 'qim/$lens.js' {
  declare module.exports: $Exports<'qim/$lens'>;
}
declare module 'qim/$merge.js' {
  declare module.exports: $Exports<'qim/$merge'>;
}
declare module 'qim/$mergeDeep.js' {
  declare module.exports: $Exports<'qim/$mergeDeep'>;
}
declare module 'qim/$nav.js' {
  declare module.exports: $Exports<'qim/$nav'>;
}
declare module 'qim/$none.js' {
  declare module.exports: $Exports<'qim/$none'>;
}
declare module 'qim/$pick.js' {
  declare module.exports: $Exports<'qim/$pick'>;
}
declare module 'qim/$pushContext.js' {
  declare module.exports: $Exports<'qim/$pushContext'>;
}
declare module 'qim/$set.js' {
  declare module.exports: $Exports<'qim/$set'>;
}
declare module 'qim/$setContext.js' {
  declare module.exports: $Exports<'qim/$setContext'>;
}
declare module 'qim/$slice.js' {
  declare module.exports: $Exports<'qim/$slice'>;
}
declare module 'qim/$traverse.js' {
  declare module.exports: $Exports<'qim/$traverse'>;
}
declare module 'qim/apply.js' {
  declare module.exports: $Exports<'qim/apply'>;
}
declare module 'qim/find.js' {
  declare module.exports: $Exports<'qim/find'>;
}
declare module 'qim/has.js' {
  declare module.exports: $Exports<'qim/has'>;
}
declare module 'qim/index' {
  declare module.exports: $Exports<'qim'>;
}
declare module 'qim/index.js' {
  declare module.exports: $Exports<'qim'>;
}
declare module 'qim/select.js' {
  declare module.exports: $Exports<'qim/select'>;
}
declare module 'qim/set.js' {
  declare module.exports: $Exports<'qim/set'>;
}
declare module 'qim/traverse.js' {
  declare module.exports: $Exports<'qim/traverse'>;
}
declare module 'qim/umd/qim.js' {
  declare module.exports: $Exports<'qim/umd/qim'>;
}
declare module 'qim/umd/qim.min.js' {
  declare module.exports: $Exports<'qim/umd/qim.min'>;
}
declare module 'qim/update.js' {
  declare module.exports: $Exports<'qim/update'>;
}
declare module 'qim/utils/arrayify.js' {
  declare module.exports: $Exports<'qim/utils/arrayify'>;
}
declare module 'qim/utils/copy.js' {
  declare module.exports: $Exports<'qim/utils/copy'>;
}
declare module 'qim/utils/createMerge.js' {
  declare module.exports: $Exports<'qim/utils/createMerge'>;
}
declare module 'qim/utils/curry.js' {
  declare module.exports: $Exports<'qim/utils/curry'>;
}
declare module 'qim/utils/getTypeErrorMessage.js' {
  declare module.exports: $Exports<'qim/utils/getTypeErrorMessage'>;
}
declare module 'qim/utils/isNextNavigatorConstant.js' {
  declare module.exports: $Exports<'qim/utils/isNextNavigatorConstant'>;
}
declare module 'qim/utils/normalizeIndex.js' {
  declare module.exports: $Exports<'qim/utils/normalizeIndex'>;
}
declare module 'qim/utils/reduced.js' {
  declare module.exports: $Exports<'qim/utils/reduced'>;
}
declare module 'qim/utils/reduceSequence.js' {
  declare module.exports: $Exports<'qim/utils/reduceSequence'>;
}
declare module 'qim/utils/removed.js' {
  declare module.exports: $Exports<'qim/utils/removed'>;
}
