// flow-typed signature: 48f3558ec2eef9b20a2feee39b863229
// flow-typed version: <<STUB>>/react-test-render_v^1.1.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-test-render/lib/index' {
  declare module.exports: any;
}

declare module 'react-test-render/lib/test-renderer' {
  declare module.exports: any;
}

declare module 'react-test-render/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-test-render/lib/index.js' {
  declare module.exports: $Exports<'react-test-render/lib/index'>;
}
declare module 'react-test-render/lib/test-renderer.js' {
  declare module.exports: $Exports<'react-test-render/lib/test-renderer'>;
}
declare module 'react-test-render/lib/utils.js' {
  declare module.exports: $Exports<'react-test-render/lib/utils'>;
}
