// flow-typed signature: aad674eafafdaa7d75d0de89a9f5f9b3
// flow-typed version: <<STUB>>/react-image-magnifiers_v^1.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-magnifiers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-magnifiers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-magnifiers/dist/GlassMagnifier' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/GlassRenderer' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/ImagePreviewOverlay' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/index' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/Magnifier' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/MagnifierRenderer' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/PictureInPictureMagnifier' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/PictureInPictureRenderer' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/SideBySideMagnifier' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/SideBySideRenderer' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/styles' {
  declare module.exports: any;
}

declare module 'react-image-magnifiers/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-magnifiers/dist/GlassMagnifier.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/GlassMagnifier'>;
}
declare module 'react-image-magnifiers/dist/GlassRenderer.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/GlassRenderer'>;
}
declare module 'react-image-magnifiers/dist/ImagePreviewOverlay.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/ImagePreviewOverlay'>;
}
declare module 'react-image-magnifiers/dist/index.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/index'>;
}
declare module 'react-image-magnifiers/dist/Magnifier.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/Magnifier'>;
}
declare module 'react-image-magnifiers/dist/MagnifierRenderer.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/MagnifierRenderer'>;
}
declare module 'react-image-magnifiers/dist/PictureInPictureMagnifier.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/PictureInPictureMagnifier'>;
}
declare module 'react-image-magnifiers/dist/PictureInPictureRenderer.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/PictureInPictureRenderer'>;
}
declare module 'react-image-magnifiers/dist/SideBySideMagnifier.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/SideBySideMagnifier'>;
}
declare module 'react-image-magnifiers/dist/SideBySideRenderer.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/SideBySideRenderer'>;
}
declare module 'react-image-magnifiers/dist/styles.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/styles'>;
}
declare module 'react-image-magnifiers/dist/utils.js' {
  declare module.exports: $Exports<'react-image-magnifiers/dist/utils'>;
}
