// flow-typed signature: 357f48a15f8d66610a6eff0c2de816f8
// flow-typed version: <<STUB>>/react-addons-create-fragment_v^15.4.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-create-fragment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-create-fragment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-addons-create-fragment/react-addons-create-fragment' {
  declare module.exports: any;
}

declare module 'react-addons-create-fragment/react-addons-create-fragment.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-addons-create-fragment/index' {
  declare module.exports: $Exports<'react-addons-create-fragment'>;
}
declare module 'react-addons-create-fragment/index.js' {
  declare module.exports: $Exports<'react-addons-create-fragment'>;
}
declare module 'react-addons-create-fragment/react-addons-create-fragment.js' {
  declare module.exports: $Exports<'react-addons-create-fragment/react-addons-create-fragment'>;
}
declare module 'react-addons-create-fragment/react-addons-create-fragment.min.js' {
  declare module.exports: $Exports<'react-addons-create-fragment/react-addons-create-fragment.min'>;
}
