export const SET_QUEST_DETAIL_PAGE_MODAL = 'SET_QUEST_DETAIL_PAGE_MODAL';
export const OPEN_QUEST_DETAIL_PAGE_MODAL = 'OPEN_QUEST_DETAIL_PAGE_MODAL';
export const CLOSE_QUEST_DETAIL_PAGE_MODAL = 'CLOSE_QUEST_DETAIL_PAGE_MODAL';
